package HaskellFun.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {

  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0b, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Definition_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new DefinitionParameter_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new DefinitionReference_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new DoExpression_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new EmptyLine_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new HaskellModule_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new Import_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new Println_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }
  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    return Collections.<ConceptEditorComponent>emptyList();
  }


  private static String[] stringSwitchCases_xbvbvu_a0a0b = new String[]{"HaskellFun.structure.Definition", "HaskellFun.structure.DefinitionParameter", "HaskellFun.structure.DefinitionReference", "HaskellFun.structure.DoExpression", "HaskellFun.structure.EmptyLine", "HaskellFun.structure.HaskellModule", "HaskellFun.structure.Import", "HaskellFun.structure.Println"};
}
