package HaskellFun.behavior;

/*Generated by MPS */

import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;

public class Constructor_BehaviorDescriptor extends AbstractConstructor_BehaviorDescriptor {
  public Constructor_BehaviorDescriptor() {
  }
  public List<SNode> virtual_parameterTypes_654027536478842950(SNode thisNode) {
    return Constructor_Behavior.virtual_parameterTypes_654027536478842950(thisNode);
  }
  @Override
  public String getConceptFqName() {
    return "HaskellFun.structure.Constructor";
  }
}
