package HaskellFun.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Type_BehaviorDescriptor;

public class ConstructorCall_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public ConstructorCall_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "HaskellFun.structure.ConstructorCall";
  }
}
