package HaskellFun.behavior;

/*Generated by MPS */


public class ConstructorRecord_BehaviorDescriptor extends AbstractConstructor_BehaviorDescriptor {
  public ConstructorRecord_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "HaskellFun.structure.ConstructorRecord";
  }
}
