package HaskellFun.behavior;

/*Generated by MPS */


public class Constructor_BehaviorDescriptor extends AbstractConstructor_BehaviorDescriptor {
  public Constructor_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "HaskellFun.structure.Constructor";
  }
}
