package HaskellFun.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class DataType_Behavior {
  public static void init(SNode thisNode) {
  }
  public static boolean call_hasTypeParameters_654027536478736239(SNode thisNode) {
    return ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getReferenceLink(0x70eb8650b1874f45L, 0x995803d27f5d94baL, 0x9139294492326ddL, 0x913929449232708L, "algebraicDataType")), MetaAdapterFactory.getContainmentLink(0x70eb8650b1874f45L, 0x995803d27f5d94baL, 0x91392944907b44dL, 0x913929449081352L, "typeVars"))).isNotEmpty();
  }
}
