package HaskellFun.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Type_BehaviorDescriptor;

public class DataType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public DataType_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "HaskellFun.structure.DataType";
  }
}
