package HaskellFun.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class DefinitionReference_BehaviorDescriptor extends Expression_BehaviorDescriptor implements HaskellExpression_BehaviorDescriptor {
  public DefinitionReference_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "HaskellFun.structure.DefinitionReference";
  }
}
