package HaskellFun.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class DoExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor implements HaskellExpression_BehaviorDescriptor {
  public DoExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "HaskellFun.structure.DoExpression";
  }
}
