package HaskellFun.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;

public class EmptyLine_BehaviorDescriptor extends Form_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor {
  public EmptyLine_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "HaskellFun.structure.EmptyLine";
  }
}
