package HaskellFun.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Form_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Form_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "HaskellFun.structure.Form";
  }
}
