package HaskellFun.behavior;

/*Generated by MPS */


public class Import_BehaviorDescriptor extends Form_BehaviorDescriptor implements HaskellExpression_BehaviorDescriptor {
  public Import_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "HaskellFun.structure.Import";
  }
}
