package HaskellFun.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class Import_BehaviorDescriptor extends Expression_BehaviorDescriptor implements HaskellExpression_BehaviorDescriptor {
  public Import_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "HaskellFun.structure.Import";
  }
}
