package HaskellFun.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class Println_BehaviorDescriptor extends Expression_BehaviorDescriptor implements HaskellExpression_BehaviorDescriptor {
  public Println_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "HaskellFun.structure.Println";
  }
}
